version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "miniconda3-3.12-24.1" # note that libmamba-solver is available since 22.1
    nodejs: "20" # maybe need to be also miniconda
  jobs:
    post_create_environment:
      - which python
      - which conda
      - echo $CONDA_PREFIX
      - python -c "import aiida_workgraph; print(aiida_workgraph.__file__)"
      - pip install .[docs]
      - pip install -r docs/requirements.txt
      - rabbitmq-server -detached
      - verdi presto
      - verdi profile configure-rabbitmq
      - verdi daemon start

conda:
  environment: docs/environment.yml

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
