version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "miniconda3-3.12-24.1" # note that libmamba-solver is available since 22.1
    nodejs: "20" # maybe need to be also miniconda
  jobs:
    post_create_environment:
      - python -m pip install --no-cache-dir .[docs]
      - python -m pip install --exists-action=w --no-cache-dir -r docs/requirements.txt
      - rabbitmq-server -detached
      - sleep 10
      - rabbitmq-diagnostics status
      - verdi presto
      - verdi daemon start
      - verdi status
      - aiida-pseudo install sssp -x PBEsol
      - verdi group list
      - cat /proc/cpuinfo | grep processor | wc -l

conda:
  environment: docs/environment.yml

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
