version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "miniconda3-3.12-24.1" # note that libmamba-solver is available since 22.1
    nodejs: "20" # maybe need to be also miniconda
  jobs:
    post_create_environment:
      - which python
      - which rabbitmq-server
      - nohup rabbitmq-server > rabbitmq_log.txt 2>&1 &
      - sleep 5
      - rabbitmq-diagnostics status


conda:
  environment: docs/environment.yml

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
