version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "miniconda3-3.12-24.1" # note that libmamba-solver is available since 22.1
    nodejs: "20" # maybe need to be also miniconda
  jobs:
    post_create_environment:
      - which python
      - which conda
      - echo $CONDA_PREFIX
      - which pip
      - which npm
      - npm --prefix aiida_workgraph/widget install
      - npm --prefix aiida_workgraph/widget run build
      - pip install --no-cache-dir .[docs]
      - pip install --exists-action=w --no-cache-dir -r docs/requirements.txt
      - pip list | grep aiida
      - rabbitmq-server -detached
      - sleep 10
      - rabbitmq-diagnostics status
      - verdi presto
      - verdi profile configure-rabbitmq
      - verdi daemon start
      - verdi status
      - pwd
      - pip list | grep aiida

conda:
  environment: docs/environment.yml

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
