name: pre-commit

on:
  push:
    branches-ignore: [gh-pages]
  pull_request:
    branches-ignore: [gh-pages]

env:
  FORCE_COLOR: 1

jobs:

  pre-commit:

    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v5

    - name: Set Up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Set up uv
      uses: astral-sh/setup-uv@v6
      with:
        version: 0.8.17
        python-version: '3.10'
        activate-environment: true

    - name: Install dependencies from uv lock
      run: uv sync --locked --extra pre-commit

    - name: Run pre-commit
      run: pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
